// allow  user to select the unit of the ingredient from the list below:
// {Unit: "pinch"},
// {Unit: "tbsp"},
// {Unit: "tsp"},
// {Unit: "cup"},
// {Unit: "pint"},
// {Unit: "quart"},
// {Unit: "gallon"},
// {Unit: "fluid ounce"},
// {Unit: "ml"},
// {Unit: "l"},
// {Unit: "pound"},
// {Unit: "mg"},
// {Unit: "g"},
// {Unit: "kg"},
